_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
augmentation_intensity:
    value: 0.3
batch_size:
    value: 128
dropout:
    value: 0.2
learning_rate:
    value: 1.006708747092229
weight_decay:
    value: 1.0026491021516324
