_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
method:
    value: bayes
metric:
    value:
        goal: maximize
        name: Validation F1
parameters:
    value:
        batch_size:
            values:
                - 32
                - 64
                - 128
        class_weights:
            values:
                - - 1
                  - 2
                - - 1
                  - 3
                - - 1
                  - 4
        dropout:
            values:
                - 0.2
                - 0.3
                - 0.4
                - 0.5
        image_size:
            values:
                - 224
                - 256
                - 288
        learning_rate:
            max: 0.001
            min: 1e-05
        min_delta:
            values:
                - 0.001
                - 0.005
                - 0.01
        patience:
            values:
                - 3
                - 5
                - 7
        use_amp:
            values:
                - true
                - false
        weight_decay:
            max: 0.001
            min: 1e-06
