_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 64
class_weights:
    value:
        - 1
        - 2
dropout:
    value: 0.3
epochs:
    value: 20
image_size:
    value: 224
learning_rate:
    value: 0.001
min_delta:
    value: 0.001
patience:
    value: 5
use_amp:
    value: true
weight_decay:
    value: 0.0001
